In [1]:
import pandas as pd
import os

try:
    os.makedirs('../transformed_zone')
except FileExistsError:
    print('Folder already exists')

Folder already exists

In [2]:
''' pt locale'''
running_pt = {'name':['Corrida a 6,4 km/h',
                      'Corrida a 6,4 km/h',
                      'Corrida a 7,5 km/h',
                      'Corrida a 7,5 km/h',
                      'Corrida a 8 km/h',
                      'Corrida a 8 km/h',
                      'Corrida a 10 km/h',
                      'Corrida a 10 km/h',
                      'Corrida a 12 km/h',
                      'Corrida a 12 km/h'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}

df_running_pt = pd.DataFrame(data=running_pt)


''' es locale '''
running_es = {'name':['Correndo a 6,4 km/h',
                      'Correndo a 6,4 km/h',
                      'Correndo a 7,5 km/h',
                      'Correndo a 7,5 km/h',
                      'Correndo a 8 km/h',
                      'Correndo a 8 km/h',
                      'Correndo a 10 km/h',
                      'Correndo a 10 km/h',
                      'Correndo a 12 km/h',
                      'Correndo a 12 km/h'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_running_es = pd.DataFrame(data=running_es)

''' fr locale'''
running_fr = {'name':['Courir à 6,4 km/h',
                      'Courir à 6,4 km/h',
                      'Courir à 7,5 km/h',
                      'Courir à 7,5 km/h',
                      'Courir à 8 km/h',
                      'Courir à 8 km/h',
                      'Courir à 10 km/h',
                      'Courir à 10 km/h',
                      'Courir à 12 km/h',
                      'Courir à 12 km/h'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_running_fr = pd.DataFrame(data=running_fr)

''' uk locale'''

running_uk = {'name':['Running at 6.4 km/h',
                      'Running at 6.4 km/h',
                      'Running at 7.5 km/h',
                      'Running at 7.5 km/h',
                      'Running at 8 km/h',
                      'Running at 8 km/h',
                      'Running at 10 km/h',
                      'Running at 10 km/h',
                      'Running at 12 km/h',
                      'Running at 12 km/h'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_running_uk = pd.DataFrame(data=running_uk)

In [3]:
df_running_fr,df_running_es,df_running_pt,df_running_uk

(                name  duration
 0  Courir à 6,4 km/h        15
 1  Courir à 6,4 km/h        30
 2  Courir à 7,5 km/h        15
 3  Courir à 7,5 km/h        30
 4    Courir à 8 km/h        15
 5    Courir à 8 km/h        30
 6   Courir à 10 km/h        15
 7   Courir à 10 km/h        30
 8   Courir à 12 km/h        15
 9   Courir à 12 km/h        30,
                   name  duration
 0  Correndo a 6,4 km/h        15
 1  Correndo a 6,4 km/h        30
 2  Correndo a 7,5 km/h        15
 3  Correndo a 7,5 km/h        30
 4    Correndo a 8 km/h        15
 5    Correndo a 8 km/h        30
 6   Correndo a 10 km/h        15
 7   Correndo a 10 km/h        30
 8   Correndo a 12 km/h        15
 9   Correndo a 12 km/h        30,
                  name  duration
 0  Corrida a 6,4 km/h        15
 1  Corrida a 6,4 km/h        30
 2  Corrida a 7,5 km/h        15
 3  Corrida a 7,5 km/h        30
 4    Corrida a 8 km/h        15
 5    Corrida a 8 km/h        30
 6   Corrida a 10 km/h        15
 7   Corrida a 10 km/h        30
 8   Corrida a 12 km/h        15
 9   Corrida a 12 km/h        30,
                   name  duration
 0  Running at 6.4 km/h        15
 1  Running at 6.4 km/h        30
 2  Running at 7.5 km/h        15
 3  Running at 7.5 km/h        30
 4    Running at 8 km/h        15
 5    Running at 8 km/h        30
 6   Running at 10 km/h        15
 7   Running at 10 km/h        30
 8   Running at 12 km/h        15
 9   Running at 12 km/h        30)

In [4]:
with open('../transformed_zone/running_pt.xml', 'w') as running_pt_xml: 
    running_pt_xml.write(df_running_pt.to_xml())

In [5]:
with open('../transformed_zone/running_es.xml', 'w') as running_es_xml: 
    running_es_xml.write(df_running_es.to_xml())

In [6]:
with open('../transformed_zone/running_fr.xml', 'w') as running_fr_xml: 
    running_fr_xml.write(df_running_fr.to_xml())

In [7]:
with open('../transformed_zone/running_uk.xml', 'w') as running_uk_xml: 
    running_uk_xml.write(df_running_uk.to_xml())

In [2]:
''' pt locale'''
walking_pt = {'name':['Caminhada com muletas',
                      'Caminhada com muletas',
                      'Caminhada lenta a 4,5 km/h',
                      'Caminhada lenta a 4,5 km/h',
                      'Caminhada na natureza',
                      'Caminhada na natureza',
                      'Caminhada rápida a 6,5 km/h',
                      'Caminhada rápida a 6,5 km/h',
                      'Caminhada nórdica',
                      'Caminhada nórdica'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}

df_walking_pt = pd.DataFrame(data=walking_pt)


''' es locale '''
walking_es = {'name':['Caminar con muletas',
                      'Caminar con muletas',
                      'Caminata lenta a 4,5 km/h ',
                      'Caminata lenta a 4,5 km/h ',
                      'Paseo por la naturaleza',
                      'Paseo por la naturaleza',
                      'Caminata rápida a 6,5 km/h',
                      'Caminata rápida a 6,5 km/h',
                      'Caminata nórdica',
                      'Caminata nórdica'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_walking_es = pd.DataFrame(data=walking_es)

''' fr locale'''
walking_fr = {'name':['Marcher avec des béquilles',
                      'Marcher avec des béquilles',
                      'Marche lente à 4,5 km/h',
                      'Marche lente à 4,5 km/h',
                      'Promenade dans la nature',
                      'Promenade dans la nature',
                      'Marche rapide à 6,5 km/h',
                      'Marche rapide à 6,5 km/h',
                      'Marche nordique',
                      'Marche nordique'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_walking_fr = pd.DataFrame(data=walking_fr)

''' uk locale'''

walking_uk = {'name':['To walk with crutches',
                      'To walk with crutches',
                      'Slow walking at 4.5 km/h',
                      'Slow walking at 4.5 km/h',
                      'Nature walk',
                      'Nature walk',
                      'Fast walking at 6.5 km/h',
                      'Fast walking at 6.5 km/h',
                      'Nordic walk',
                      'Nordic walk'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_walking_uk = pd.DataFrame(data=walking_uk)

In [9]:
df_walking_uk,df_walking_es,df_walking_pt,df_walking_fr

(                       name  duration
 0     To walk with crutches        15
 1     To walk with crutches        30
 2  Slow walking at 4.5 km/h        15
 3  Slow walking at 4.5 km/h        30
 4               Nature walk        15
 5               Nature walk        30
 6  Fast walking at 6.5 km/h        15
 7  Fast walking at 6.5 km/h        30
 8               Nordic walk        15
 9               Nordic walk        30,
                          name  duration
 0         Caminar con muletas        15
 1         Caminar con muletas        30
 2  Caminata lenta a 4,5 km/h         15
 3  Caminata lenta a 4,5 km/h         30
 4     Paseo por la naturaleza        15
 5     Paseo por la naturaleza        30
 6  Caminata rápida a 6,5 km/h        15
 7  Caminata rápida a 6,5 km/h        30
 8            Caminata nórdica        15
 9            Caminata nórdica        30,
                           name  duration
 0        Caminhada com muletas        15
 1        Caminhada com muletas        30
 2   Caminhada lenta a 4,5 km/h        15
 3   Caminhada lenta a 4,5 km/h        30
 4        Caminhada na natureza        15
 5        Caminhada na natureza        30
 6  Caminhada rápida a 6,5 km/h        15
 7  Caminhada rápida a 6,5 km/h        30
 8            Caminhada nórdica        15
 9            Caminhada nórdica        30,
                          name  duration
 0  Marcher avec des béquilles        15
 1  Marcher avec des béquilles        30
 2     Marche lente à 4,5 km/h        15
 3     Marche lente à 4,5 km/h        30
 4    Promenade dans la nature        15
 5    Promenade dans la nature        30
 6    Marche rapide à 6,5 km/h        15
 7    Marche rapide à 6,5 km/h        30
 8             Marche nordique        15
 9             Marche nordique        30)

In [3]:
with open('../transformed_zone/walking_pt.xml', 'w') as walking_pt_xml: 
    walking_pt_xml.write(df_walking_pt.to_xml())

with open('../transformed_zone/walking_es.xml', 'w') as walking_es_xml: 
    walking_es_xml.write(df_walking_es.to_xml())

with open('../transformed_zone/walking_fr.xml', 'w') as walking_fr_xml: 
    walking_fr_xml.write(df_walking_fr.to_xml())
    
with open('../transformed_zone/walking_uk.xml', 'w') as walking_uk_xml: 
    walking_uk_xml.write(df_walking_uk.to_xml())

In [11]:
''' pt locale'''
cycling_pt = {'name':['Ciclismo em estrada',
                      'Ciclismo em estrada',
                      'Ciclismo de alto impacto',
                      'Ciclismo de alto impacto',
                      'Ciclismo de médio impacto',
                      'Ciclismo de médio impacto',
                      'Passeio de bicicleta a 10 km/h',
                      'Passeio de bicicleta a 10 km/h',
                      'Passeio de bicicleta a 12,5 km/h',
                      'Passeio de bicicleta a 12,5 km/h'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}

df_cycling_pt = pd.DataFrame(data=cycling_pt)


''' es locale '''
cycling_es = {'name':['Ciclismo de carretera',
                      'Ciclismo de carretera',
                      'Ciclismo de alto impacto',
                      'Ciclismo de alto impacto',
                      'Ciclismo de medio impacto',
                      'Ciclismo de medio impacto',
                      'Paseo en bicicleta a 10 km/h',
                      'Paseo en bicicleta a 10 km/h',
                      'Paseo en bicicleta a 12,5 km/h',
                      'Paseo en bicicleta a 12,5 km/h'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_cycling_es = pd.DataFrame(data=cycling_es)

''' fr locale'''
cycling_fr= {'name':['Cyclisme sur route',
                      'Cyclisme sur route',
                      'Cyclisme à fort impact',
                      'Cyclisme à fort impact',
                      'Cyclisme à impact moyen',
                      'Cyclisme à impact moyen',
                      'Balade à vélo à 10 km/h',
                      'Balade à vélo à 10 km/h',
                      'Balade à vélo à 12,5 km/h',
                      'Balade à vélo à 12,5 km/h'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_cycling_fr = pd.DataFrame(data=cycling_fr)

''' uk locale'''

cycling_uk = {'name':['Road cycling',
                      'Road cycling',
                      'High impact cycling',
                      'High impact cycling',
                      'Medium impact cycling',
                      'Medium impact cycling',
                      'Bike ride at 10 km/h',
                      'Bike ride at 10 km/h',
                      'Bike ride at 12.5 km/h ',
                      'Bike ride at 12.5 km/h '
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_cycling_uk = pd.DataFrame(data=cycling_uk)

In [12]:
df_cycling_uk, df_cycling_es, df_cycling_pt, df_cycling_fr

(                      name  duration
 0             Road cycling        15
 1             Road cycling        30
 2      High impact cycling        15
 3      High impact cycling        30
 4    Medium impact cycling        15
 5    Medium impact cycling        30
 6     Bike ride at 10 km/h        15
 7     Bike ride at 10 km/h        30
 8  Bike ride at 12.5 km/h         15
 9  Bike ride at 12.5 km/h         30,
                              name  duration
 0           Ciclismo de carretera        15
 1           Ciclismo de carretera        30
 2        Ciclismo de alto impacto        15
 3        Ciclismo de alto impacto        30
 4       Ciclismo de medio impacto        15
 5       Ciclismo de medio impacto        30
 6    Paseo en bicicleta a 10 km/h        15
 7    Paseo en bicicleta a 10 km/h        30
 8  Paseo en bicicleta a 12,5 km/h        15
 9  Paseo en bicicleta a 12,5 km/h        30,
                                name  duration
 0               Ciclismo em estrada        15
 1               Ciclismo em estrada        30
 2          Ciclismo de alto impacto        15
 3          Ciclismo de alto impacto        30
 4         Ciclismo de médio impacto        15
 5         Ciclismo de médio impacto        30
 6    Passeio de bicicleta a 10 km/h        15
 7    Passeio de bicicleta a 10 km/h        30
 8  Passeio de bicicleta a 12,5 km/h        15
 9  Passeio de bicicleta a 12,5 km/h        30,
                         name  duration
 0         Cyclisme sur route        15
 1         Cyclisme sur route        30
 2     Cyclisme à fort impact        15
 3     Cyclisme à fort impact        30
 4    Cyclisme à impact moyen        15
 5    Cyclisme à impact moyen        30
 6    Balade à vélo à 10 km/h        15
 7    Balade à vélo à 10 km/h        30
 8  Balade à vélo à 12,5 km/h        15
 9  Balade à vélo à 12,5 km/h        30)

In [13]:
with open('../transformed_zone/cycling_pt.xml', 'w') as cycling_pt_xml: 
    cycling_pt_xml.write(df_cycling_pt.to_xml())

In [14]:
with open('../transformed_zone/cycling_es.xml', 'w') as cycling_es_xml: 
    cycling_es_xml.write(df_cycling_es.to_xml())

In [15]:
with open('../transformed_zone/cycling_fr.xml', 'w') as cycling_fr_xml: 
    cycling_fr_xml.write(df_cycling_fr.to_xml())

In [16]:
with open('../transformed_zone/cycling_uk.xml', 'w') as cycling_uk_xml: 
    cycling_uk_xml.write(df_cycling_uk.to_xml())

In [17]:
''' pt locale'''
gym_pt = {'name':[    'Treino leve de membros',
                      'Treino leve de membros',
                      'Treino leve de perna',
                      'Treino leve de perna',
                      'Treino pesado de membros',
                      'Treino pesado de membros',
                      'AbSolution (LesMills)',
                      'AbSolution (LesMills)',
                      'BODYATTACK (LesMills)',
                      'BODYATTACK (LesMills)'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}

df_gym_pt = pd.DataFrame(data=gym_pt)


''' es locale '''
gym_es = {'name':[    'Entrenamiento de extremidades ligeras',
                      'Entrenamiento de extremidades ligeras',
                      'Entrenamiento ligero de piernas',
                      'Entrenamiento ligero de piernas',
                      'Entrenamiento de extremidades pesadas',
                      'Entrenamiento de extremidades pesadas',
                      'AbSolution (LesMills)',
                      'AbSolution (LesMills)',
                      'BODYATTACK (LesMills)',
                      'BODYATTACK (LesMills)'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_gym_es = pd.DataFrame(data=gym_es)

''' fr locale'''
gym_fr= {'name':[     'Formation des membres légers',
                      'Formation des membres légers',
                      'Entraînement jambes légères',
                      'Entraînement jambes légères',
                      'Entraînement des membres lourds',
                      'Entraînement des membres lourds',
                      'AbSolution (LesMills)',
                      'AbSolution (LesMills)',
                      'BODYATTACK (LesMills)',
                      'BODYATTACK (LesMills)'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_gym_fr = pd.DataFrame(data=gym_fr)

''' uk locale'''

gym_uk = {'name':[    'Light limb training',
                      'Light limb training',
                      'Light legs training',
                      'Light legs training',
                      'Heavy Limb Training',
                      'Heavy Limb Training',
                      'AbSolution (LesMills)',
                      'AbSolution (LesMills)',
                      'BODYATTACK (LesMills)',
                      'BODYATTACK (LesMills)'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_gym_uk = pd.DataFrame(data=gym_uk)

In [18]:
df_gym_uk,df_gym_pt,df_gym_es,df_gym_fr

(                    name  duration
 0    Light limb training        15
 1    Light limb training        30
 2    Light legs training        15
 3    Light legs training        30
 4    Heavy Limb Training        15
 5    Heavy Limb Training        30
 6  AbSolution (LesMills)        15
 7  AbSolution (LesMills)        30
 8  BODYATTACK (LesMills)        15
 9  BODYATTACK (LesMills)        30,
                        name  duration
 0    Treino leve de membros        15
 1    Treino leve de membros        30
 2      Treino leve de perna        15
 3      Treino leve de perna        30
 4  Treino pesado de membros        15
 5  Treino pesado de membros        30
 6     AbSolution (LesMills)        15
 7     AbSolution (LesMills)        30
 8     BODYATTACK (LesMills)        15
 9     BODYATTACK (LesMills)        30,
                                     name  duration
 0  Entrenamiento de extremidades ligeras        15
 1  Entrenamiento de extremidades ligeras        30
 2        Entrenamiento ligero de piernas        15
 3        Entrenamiento ligero de piernas        30
 4  Entrenamiento de extremidades pesadas        15
 5  Entrenamiento de extremidades pesadas        30
 6                  AbSolution (LesMills)        15
 7                  AbSolution (LesMills)        30
 8                  BODYATTACK (LesMills)        15
 9                  BODYATTACK (LesMills)        30,
                               name  duration
 0     Formation des membres légers        15
 1     Formation des membres légers        30
 2      Entraînement jambes légères        15
 3      Entraînement jambes légères        30
 4  Entraînement des membres lourds        15
 5  Entraînement des membres lourds        30
 6            AbSolution (LesMills)        15
 7            AbSolution (LesMills)        30
 8            BODYATTACK (LesMills)        15
 9            BODYATTACK (LesMills)        30)

In [19]:
with open('../transformed_zone/gym_es.xml', 'w') as gym_es_xml: 
    gym_es_xml.write(df_gym_es.to_xml())

In [20]:
with open('../transformed_zone/gym_pt.xml', 'w') as gym_pt_xml: 
    gym_pt_xml.write(df_gym_pt.to_xml())

In [21]:
with open('../transformed_zone/gym_uk.xml', 'w') as gym_uk_xml: 
    gym_uk_xml.write(df_gym_uk.to_xml())

In [ ]:
with open('../transformed_zone/gym_es.xml', 'w') as gym_es_xml: 
    gym_es_xml.write(df_gym_es.to_xml())

In [24]:
''' pt locale'''
group_sports_pt = {'name':['Futebol de 11',
                      'Futebol de 11',
                      'Futsal',
                      'Futsal',
                      'Basquetebol',
                      'Basquetebol',
                      'Voleibol',
                      'Voleibol',
                      'Andebol',
                      'Andebol'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}

df_group_sports_pt = pd.DataFrame(data=group_sports_pt)


''' es locale '''
group_sports_es = {'name':[ 'Fútbol 11',
                      'Fútbol 11',
                      'Fútbol sala',
                      'Fútbol sala',
                      'Baloncesto',
                      'Baloncesto',
                      'Vóleibol',
                      'Vóleibol',
                      'Balonmano',
                      'Balonmano'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_group_sports_es = pd.DataFrame(data=group_sports_es)

''' fr locale'''
group_sports_fr= {'name':[     'Foot 11',
                      'Foot 11',
                      'Foot en salle',
                      'Foot en salle',
                      'Basket-ball',
                      'Basket-ball',
                      'Volley-ball',
                      'Volley-ball',
                      'Handball',
                      'Handball'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_group_sports_fr = pd.DataFrame(data=group_sports_fr)

''' uk locale'''

group_sports_uk = {'name':[    'Football',
                      'Football',
                      'Footsall',
                      'Footsall',
                      'Basket-ball',
                      'Basket-ball',
                      'Volley-ball',
                      'Volley-ball',
                      'Hand-ball',
                      'Hand-ball'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_group_sports_uk = pd.DataFrame(data=group_sports_uk)

In [25]:
df_group_sports_uk, df_group_sports_fr,df_group_sports_pt,df_group_sports_es

(          name  duration
 0     Football        15
 1     Football        30
 2     Footsall        15
 3     Footsall        30
 4  Basket-ball        15
 5  Basket-ball        30
 6  Volley-ball        15
 7  Volley-ball        30
 8    Hand-ball        15
 9    Hand-ball        30,
             name  duration
 0        Foot 11        15
 1        Foot 11        30
 2  Foot en salle        15
 3  Foot en salle        30
 4    Basket-ball        15
 5    Basket-ball        30
 6    Volley-ball        15
 7    Volley-ball        30
 8       Handball        15
 9       Handball        30,
             name  duration
 0  Futebol de 11        15
 1  Futebol de 11        30
 2         Futsal        15
 3         Futsal        30
 4    Basquetebol        15
 5    Basquetebol        30
 6       Voleibol        15
 7       Voleibol        30
 8        Andebol        15
 9        Andebol        30,
           name  duration
 0    Fútbol 11        15
 1    Fútbol 11        30
 2  Fútbol sala        15
 3  Fútbol sala        30
 4   Baloncesto        15
 5   Baloncesto        30
 6     Vóleibol        15
 7     Vóleibol        30
 8    Balonmano        15
 9    Balonmano        30)

In [26]:
with open('../transformed_zone/group_sports_pt.xml', 'w') as group_sports_pt_xml: 
    group_sports_pt_xml.write(df_group_sports_pt.to_xml())

In [ ]:
with open('../transformed_zone/group_sports_es.xml', 'w') as group_sports_es_xml: 
    group_sports_es_xml.write(df_group_sports_es.to_xml())

In [27]:
with open('../transformed_zone/group_sports_fr.xml', 'w') as group_sports_fr_xml: 
    group_sports_fr_xml.write(df_group_sports_fr.to_xml())

In [28]:
with open('../transformed_zone/group_sports_uk.xml', 'w') as group_sports_uk_xml: 
    group_sports_uk_xml.write(df_group_sports_uk.to_xml())

In [29]:
''' pt locale'''
swimming_pt = {'name':['Natação de baixo impacto',
                      'Natação de baixo impacto',
                      'Natação backstroke',
                      'Natação backstroke',
                      'Natação butterfly',
                      'Natação butterfly',
                      'Natação de médio impacto',
                      'Natação de médio impacto',
                      'Natação de lazer',
                      'Natação de lazer'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}

df_swimming_pt = pd.DataFrame(data=swimming_pt)


''' es locale '''
swimming_es = {'name':[ 'Natación de bajo impacto',
                      'Natación de bajo impacto',
                      'Natación backstroke',
                      'Natación backstroke',
                      'Natación butterfly',
                      'Natación butterfly',
                      'Natación de medio impacto',
                      'Natación de medio impacto',
                      'Natación de ocio',
                      'Natación de ocio'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_swimming_es = pd.DataFrame(data=swimming_es)

''' fr locale'''
swimming_fr= {'name':['Natation à faible impact',
                      'Natation à faible impact',
                      'Nage à backstroke',
                      'Nage à backstroke',
                      'Nage à butterfly',
                      'Nage à butterfly',
                      'Nage à impact moyen',
                      'Nage à impact moyen',
                      'Natation de loisir',
                      'Natation de loisir'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_swimming_fr = pd.DataFrame(data=swimming_fr)

''' uk locale'''

swimming_uk = {'name':['Low impact swimming',
                      'Low impact swimming',
                      'Backstroke swimming',
                      'Backstroke swimming',
                      'Butterfly swimming',
                      'Butterfly swimming',
                      'Medium impact swimming',
                      'Medium impact swimming',
                      'Recreational swimming',
                      'Recreational swimming'
                     ],
              'duration': [15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30,
                           15,
                           30]}
df_swimming_uk = pd.DataFrame(data=swimming_uk)

In [30]:
df_swimming_uk, df_swimming_pt, df_swimming_es,df_swimming_fr

(                     name  duration
 0     Low impact swimming        15
 1     Low impact swimming        30
 2     Backstroke swimming        15
 3     Backstroke swimming        30
 4      Butterfly swimming        15
 5      Butterfly swimming        30
 6  Medium impact swimming        15
 7  Medium impact swimming        30
 8   Recreational swimming        15
 9   Recreational swimming        30,
                        name  duration
 0  Natação de baixo impacto        15
 1  Natação de baixo impacto        30
 2        Natação backstroke        15
 3        Natação backstroke        30
 4         Natação butterfly        15
 5         Natação butterfly        30
 6  Natação de médio impacto        15
 7  Natação de médio impacto        30
 8          Natação de lazer        15
 9          Natação de lazer        30,
                         name  duration
 0   Natación de bajo impacto        15
 1   Natación de bajo impacto        30
 2        Natación backstroke        15
 3        Natación backstroke        30
 4         Natación butterfly        15
 5         Natación butterfly        30
 6  Natación de medio impacto        15
 7  Natación de medio impacto        30
 8           Natación de ocio        15
 9           Natación de ocio        30,
                        name  duration
 0  Natation à faible impact        15
 1  Natation à faible impact        30
 2         Nage à backstroke        15
 3         Nage à backstroke        30
 4          Nage à butterfly        15
 5          Nage à butterfly        30
 6       Nage à impact moyen        15
 7       Nage à impact moyen        30
 8        Natation de loisir        15
 9        Natation de loisir        30)

In [37]:
with open('../transformed_zone/swimming_pt.xml', 'w') as swimming_pt_xml: 
    swimming_pt_xml.write(df_swimming_pt.to_xml())

In [38]:
with open('../transformed_zone/swimming_es.xml', 'w') as swimming_es_xml: 
    swimming_es_xml.write(df_swimming_es.to_xml())

In [39]:
with open('../transformed_zone/swimming_fr.xml', 'w') as swimming_fr_xml: 
    swimming_fr_xml.write(df_swimming_fr.to_xml())

In [40]:
with open('../transformed_zone/swimming_uk.xml', 'w') as swimming_uk_xml: 
    swimming_uk_xml.write(df_swimming_uk.to_xml())